-- Script de correction du schéma de la table 'acte'
ALTER TABLE acte MODIFY COLUMN statut ENUM('NAISSANCE', 'MARIAGE', 'DECES', 'EN_ATTENTE_CONJOINT', 'EN_ATTENTE_OFFICIER', 'OFFICIEL', 'REFUSE') DEFAULT 'EN_ATTENTE_CONJOINT';
